# Generated by Django 5.2.17 on 2026-09-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumery', '0003_deliverystate'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystate',
            name='estimated_days',
            field=models.CharField(default='1–3 business days', max_length=40),
        ),
    ]
