# Generated by Django 5.2.17 on 2026-09-27 19:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def preserve_delivery_states(apps, schema_editor):
    DeliveryState = apps.get_model('perfumery', 'DeliveryState')
    State = apps.get_model('perfumery', 'State')
    LocalGovernment = apps.get_model('perfumery', 'LocalGovernment')
    database = schema_editor.connection.alias

    for old_delivery_state in DeliveryState.objects.using(database).all():
        state = State.objects.using(database).create(
            name=old_delivery_state.name,
            is_active=old_delivery_state.is_active,
        )
        LocalGovernment.objects.using(database).create(
            state=state,
            name=old_delivery_state.name,
            delivery_fee=old_delivery_state.delivery_fee,
            estimated_days=old_delivery_state.estimated_days,
            is_active=old_delivery_state.is_active,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('perfumery', '0004_deliverystate_estimated_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGovernment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('delivery_fee', models.DecimalField(decimal_places=2, help_text='Delivery fee in Nigerian naira (NGN).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_days', models.CharField(default='1–3 business days', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'local government',
                'verbose_name_plural': 'local governments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='localgovernment',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='perfumery.state'),
        ),
        migrations.AddConstraint(
            model_name='localgovernment',
            constraint=models.UniqueConstraint(fields=('state', 'name'), name='unique_lga_name_per_state'),
        ),
        migrations.RunPython(preserve_delivery_states, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='DeliveryState',
        ),
    ]
