# Generated by Django 5.2.17 on 2026-09-27 20:10

import django.core.validators
from django.db import migrations, models


STATE_DATA = {
    'NG-LA': ('Lagos', (
        'Agege', 'Ajeromi-Ifelodun', 'Alimosho', 'Amuwo-Odofin', 'Apapa', 'Badagry',
        'Epe', 'Eti-Osa', 'Ibeju-Lekki', 'Ifako-Ijaiye', 'Ikeja', 'Ikorodu', 'Kosofe',
        'Lagos Island', 'Lagos Mainland', 'Mushin', 'Ojo', 'Oshodi-Isolo', 'Shomolu', 'Surulere',
    )),
    'NG-OG': ('Ogun', (
        'Abeokuta North', 'Abeokuta South', 'Ado-Odo/Ota', 'Ewekoro', 'Ifo', 'Ijebu East',
        'Ijebu North', 'Ijebu North East', 'Ijebu Ode', 'Ikenne', 'Imeko Afon', 'Ipokia',
        'Obafemi Owode', 'Odeda', 'Odogbolu', 'Ogun Waterside', 'Remo North', 'Sagamu',
        'Yewa North', 'Yewa South',
    )),
    'NG-FC': ('FCT Abuja', ('Abaji', 'AMAC', 'Bwari', 'Gwagwalada', 'Kuje', 'Kwali')),
}
STATE_ALIASES = {
    'lagos': 'NG-LA', 'lagos state': 'NG-LA',
    'ogun': 'NG-OG', 'ogun state': 'NG-OG',
    'fct': 'NG-FC', 'fct abuja': 'NG-FC', 'abuja': 'NG-FC',
    'federal capital territory': 'NG-FC',
}


def populate_state_codes_and_lgas(apps, schema_editor):
    State = apps.get_model('perfumery', 'State')
    LocalGovernment = apps.get_model('perfumery', 'LocalGovernment')
    database = schema_editor.connection.alias

    for state in State.objects.using(database).all():
        code = state.code or STATE_ALIASES.get(state.name.strip().casefold())
        if not code:
            continue
        canonical_name, lga_names = STATE_DATA[code]
        State.objects.using(database).filter(pk=state.pk).update(code=code, name=canonical_name)
        official_names = set(lga_names)
        LocalGovernment.objects.using(database).filter(state_id=state.pk).exclude(name__in=official_names).update(is_active=False)
        for lga_name in lga_names:
            LocalGovernment.objects.using(database).get_or_create(
                state_id=state.pk,
                name=lga_name,
                defaults={'delivery_fee': 0, 'estimated_days': '1–3 business days', 'is_active': True},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('perfumery', '0005_localgovernment_state_delete_deliverystate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='code',
            field=models.CharField(blank=True, choices=[('NG-LA', 'Lagos'), ('NG-OG', 'Ogun'), ('NG-FC', 'FCT Abuja')], max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='localgovernment',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery fee in Nigerian naira (NGN).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.RunPython(populate_state_codes_and_lgas, migrations.RunPython.noop),
    ]
