# Generated by Django 5.2.17 on 2026-09-27 20:35

import django.core.validators
from django.db import migrations, models


def normalize_legacy_state_codes(apps, schema_editor):
    State = apps.get_model('perfumery', 'State')
    database = schema_editor.connection.alias
    legacy_codes = {'NG-LA': 'LA', 'NG-OG': 'OG', 'NG-FC': 'FC'}
    for state in State.objects.using(database).exclude(code__isnull=True):
        if state.code in legacy_codes:
            State.objects.using(database).filter(pk=state.pk).update(code=legacy_codes[state.code])
        elif len(state.code) > 2:
            State.objects.using(database).filter(pk=state.pk).update(code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('perfumery', '0006_state_code_alter_localgovernment_delivery_fee_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_legacy_state_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='localgovernment',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Delivery fee in Nigerian naira (NGN).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
