# Generated by Django 5.2.17 on 2026-09-27 20:56

from django.db import migrations, models


def restrict_active_states(apps, schema_editor):
    State = apps.get_model('perfumery', 'State')
    database = schema_editor.connection.alias
    State.objects.using(database).all().update(is_active=False)
    State.objects.using(database).filter(code__in=('LA', 'OG', 'FC')).update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('perfumery', '0009_merge_legacy_amac'),
    ]

    operations = [
        migrations.RunPython(restrict_active_states, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='state',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
