# Generated by Django 5.2.17 on 2026-09-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumery', '0010_alter_state_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume_ml',
            field=models.PositiveIntegerField(default=100, help_text='Bottle size in millilitres (ml).'),
        ),
    ]
