# Generated by Django 5.2.17 on 2026-09-27 21:34

import django.core.validators
from django.db import migrations, models


def set_standard_delivery_fee(apps, schema_editor):
    LocalGovernment = apps.get_model('perfumery', 'LocalGovernment')
    LocalGovernment.objects.using(schema_editor.connection.alias).all().update(delivery_fee=3000)


class Migration(migrations.Migration):

    dependencies = [
        ('perfumery', '0011_product_volume_ml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localgovernment',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=3000, help_text='Delivery fee in Nigerian naira (NGN).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RunPython(set_standard_delivery_fee, migrations.RunPython.noop),
    ]
