# Generated by Django 5.2.17 on 2026-09-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumery', '0014_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
    ]
